name: Sub-Task
description: Create a Sub-Task that relates to a Task
title: "[SUBTASK] "
labels: ["sub-task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Sub-Task Information
        
        ⚠️ **IMPORTANT: Sub-Tasks must be created as sub-issues of a Task.**
        
        ### How to Create:
        1. Navigate to the parent Task issue
        2. Click "Create sub-issue" at the bottom of the issue description
        3. Select this Sub-Task template
        
        ### Alternatively:
        If you create this issue first, you must:
        1. Navigate to the parent Task issue
        2. Click the dropdown next to "Create sub-issue"
        3. Select "Add existing issue" and link this issue
        
        Sub-Tasks can have their own sub-issues (up to 8 levels of nesting).
        
  - type: input
    id: subtask-title
    attributes:
      label: Sub-Task Title
      description: A clear, concise title for this sub-task
      placeholder: "e.g., Write unit tests for login validation"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of this sub-task
      placeholder: Describe what needs to be done
    validations:
      required: true
      
  - type: textarea
    id: completion-criteria
    attributes:
      label: Completion Criteria
      description: How will we know this sub-task is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
      
  - type: dropdown
    id: estimated-hours
    attributes:
      label: Estimated Hours
      description: Time estimate in hours
      options:
        - Not Estimated
        - "1 hour"
        - "2 hours"
        - "4 hours"
        - "8 hours"
        - "1 day"
    validations:
      required: false
      
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional context or implementation details
    validations:
      required: false
