name: Task
description: Create a Task that relates to a User Story
title: "[TASK] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Task Information
        
        ⚠️ **IMPORTANT: Tasks must be created as sub-issues of a User Story.**
        
        ### How to Create:
        1. Navigate to the parent User Story issue
        2. Click "Create sub-issue" at the bottom of the issue description
        3. Select this Task template
        
        ### Alternatively:
        If you create this issue first, you must:
        1. Navigate to the parent User Story issue
        2. Click the dropdown next to "Create sub-issue"
        3. Select "Add existing issue" and link this issue
        
        Tasks can only have Sub-Tasks as sub-issues.
        
  - type: input
    id: task-title
    attributes:
      label: Task Title
      description: A clear, concise title for this task
      placeholder: "e.g., Implement login form validation"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of what needs to be done
      placeholder: Describe the task in detail
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specific criteria to determine when this task is complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
      
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of work is this?
      options:
        - Development
        - Design
        - Documentation
        - Testing
        - Research
        - Configuration
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: estimated-hours
    attributes:
      label: Estimated Hours
      description: Time estimate in hours (optional)
      options:
        - Not Estimated
        - "1-2 hours"
        - "2-4 hours"
        - "4-8 hours"
        - "1 day"
        - "2-3 days"
        - "1 week"
        - "2+ weeks"
    validations:
      required: false
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Technical details, approach, or implementation notes
      placeholder: Any technical considerations or approach
    validations:
      required: false
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies on other tasks
      placeholder: Links to related issues or blockers
    validations:
      required: false
