name: User Story
description: Create a User Story that relates to a Theme
title: "[STORY] "
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Information
        
        ⚠️ **IMPORTANT: User Stories must be created as sub-issues of a Theme.**
        
        ### How to Create:
        1. Navigate to the parent Theme issue
        2. Click "Create sub-issue" at the bottom of the issue description
        3. Select this User Story template
        
        ### Alternatively:
        If you create this issue first, you must:
        1. Navigate to the parent Theme issue
        2. Click the dropdown next to "Create sub-issue"
        3. Select "Add existing issue" and link this issue
        
        User Stories can only have Tasks as sub-issues.
        
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write the user story in standard format
      placeholder: "As a [role], I want [feature] so that [benefit]"
      value: "As a , I want  so that "
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide additional context and details
      placeholder: Explain the user story in more detail
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this story to be complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this user story?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: dropdown
    id: estimated-hours
    attributes:
      label: Estimated Hours
      description: Estimated effort (optional - can be added during planning)
      options:
        - Not Estimated
        - "1-4 hours"
        - "4-8 hours"
        - "1-2 days"
        - "2-5 days"
        - "1-2 weeks"
        - "2-4 weeks"
        - "1+ months"
    validations:
      required: false
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies on other stories or themes
      placeholder: Links to related issues or external dependencies
    validations:
      required: false
      
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional context or technical considerations
    validations:
      required: false
